// lib/config/app_config.dart
// Auto-generated by spin-up.sh - DO NOT EDIT MANUALLY
// Regenerated on each spin-up

/// Backend API base URL
const String kApiBaseUrl = 'http://10.111.27.201:3000';

/// Mapbox access token
const String kMapboxAccessToken = 'pk.eyJ1IjoidGlhZ29tYXJxdWVzIiwiYSI6ImNtaW5zeHoweTB3MWkzZXNidmxmd29wamkifQ.wieB0AYuGHF-qVRTqmFQ2Q';

/// OTP base URL (for direct access if needed)
const String kOtpBaseUrl = 'http://10.111.27.201:8080';

/// Network configuration
class AppConfig {
  static const String apiBaseUrl = kApiBaseUrl;
  static const String mapboxToken = kMapboxAccessToken;
  static const String otpBaseUrl = kOtpBaseUrl;
  
  // Service URLs
  static const String backendUrl = 'http://10.111.27.201:3000';
  static const String otpUrl = 'http://10.111.27.201:8080';
}
