#!/bin/bash

# ===========================================
# Modular Spin-Up Script
# Automatically detects IPs and configures all service URLs
# Works with Windows + WSL setup
# ===========================================

set -e  # Exit on error

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}🚀 Starting Modular Spin-Up...${NC}\n"

# ===========================================
# 1. Detect Windows Host IP (LAN/Wi-Fi IP, not WSL adapter)
# ===========================================

echo -e "${YELLOW}📡 Detecting Windows LAN IP (Wi-Fi/Ethernet)...${NC}"

# Method 1: Extract Wi-Fi adapter IPv4 from ipconfig
# Look for Wi-Fi section and extract the first valid IPv4 address
WINDOWS_HOST_IP=$(powershell.exe -Command "ipconfig" 2>/dev/null | \
  awk '
    BEGIN { in_wifi=0 }
    /Wi-Fi|Wireless LAN adapter Wi-Fi/ { in_wifi=1; next }
    in_wifi && /IPv4 Address/ {
      # Extract IP using regex match
      if (match($0, /([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})/)) {
        ip = substr($0, RSTART, RLENGTH)
        # Exclude WSL (172.16-31.x), link-local (169.254.x), loopback (127.x)
        if (ip !~ /^172\.(1[6-9]|2[0-9]|3[0-1])\./ && ip !~ /^169\.254\./ && ip !~ /^127\./) {
          print ip
          exit
        }
      }
    }
    /^[A-Z]/ && in_wifi && !/Wi-Fi/ { in_wifi=0 }
  ' | head -1)

# Method 2: Fallback - try Ethernet adapter
if [ -z "$WINDOWS_HOST_IP" ] || [ -z "${WINDOWS_HOST_IP// }" ]; then
  WINDOWS_HOST_IP=$(powershell.exe -Command "ipconfig" 2>/dev/null | \
    awk '
      /Ethernet adapter/ && !/WSL/ && !/Bluetooth/ {
        ethernet_section=1
        next
      }
      ethernet_section && /IPv4 Address/ {
        gsub(/.*IPv4 Address[^:]*:[ ]*/, "")
        gsub(/[ \r\n]/, "")
        if ($0 !~ /^172\./ && $0 !~ /^169\.254\./ && $0 !~ /^127\./ && $0 ~ /^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/) {
          print $0
          exit
        }
      }
      /^[A-Z]/ && ethernet_section {
        ethernet_section=0
      }
    ' | head -1)
fi

# Method 3: Fallback - get any non-WSL, non-link-local IPv4
# Extract all IPv4 addresses and filter out WSL/loopback/link-local
if [ -z "$WINDOWS_HOST_IP" ] || [ -z "${WINDOWS_HOST_IP// }" ]; then
  WINDOWS_HOST_IP=$(powershell.exe -Command "ipconfig" 2>/dev/null | \
    grep -i "IPv4" | \
    grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | \
    grep -vE '^172\.(1[6-9]|2[0-9]|3[0-1])\.|^169\.254\.|^127\.' | \
    # Prefer 10.x or 192.168.x addresses
    grep -E '^10\.|^192\.168\.' | head -1)
  
  # If no 10.x or 192.168.x found, get any valid IP
  if [ -z "$WINDOWS_HOST_IP" ] || [ -z "${WINDOWS_HOST_IP// }" ]; then
    WINDOWS_HOST_IP=$(powershell.exe -Command "ipconfig" 2>/dev/null | \
      grep -i "IPv4" | \
      grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | \
      grep -vE '^172\.(1[6-9]|2[0-9]|3[0-1])\.|^169\.254\.|^127\.' | \
      head -1)
  fi
fi

# Method 4: Fallback - get default gateway (Windows host IP in WSL2)
if [ -z "$WINDOWS_HOST_IP" ] || [ -z "${WINDOWS_HOST_IP// }" ]; then
  WINDOWS_HOST_IP=$(ip route show | grep -i default | awk '{ print $3}' | head -1)
fi

if [ -z "$WINDOWS_HOST_IP" ] || [ -z "${WINDOWS_HOST_IP// }" ]; then
  echo -e "${RED}❌ Could not detect Windows LAN IP. Please set WINDOWS_HOST_IP manually.${NC}"
  echo -e "${YELLOW}   Example: export WINDOWS_HOST_IP=\"10.111.27.201\"${NC}"
  exit 1
fi

echo -e "${GREEN}✅ Windows LAN IP detected: ${WINDOWS_HOST_IP}${NC}\n"

# ===========================================
# 2. Detect WSL IP (for services running in WSL)
# ===========================================

echo -e "${YELLOW}📡 Detecting WSL IP...${NC}"

# Get WSL IP address
WSL_IP=$(hostname -I | awk '{print $1}')

if [ -z "$WSL_IP" ]; then
  WSL_IP="127.0.0.1"
fi

echo -e "${GREEN}✅ WSL IP detected: ${WSL_IP}${NC}\n"

# ===========================================
# 3. Service Ports Configuration
# ===========================================

BACKEND_PORT=3000
OTP_PORT=8080
POSTGRES_PORT=5432
REDIS_PORT=6379
MONGO_PORT=27017

# ===========================================
# 4. Generate Backend .env file
# ===========================================

echo -e "${YELLOW}⚙️  Generating backend/.env...${NC}"

BACKEND_ENV_FILE="backend/.env"

cat > "$BACKEND_ENV_FILE" << EOF
# Auto-generated by spin-up.sh - DO NOT EDIT MANUALLY
# Regenerated on each spin-up

# Database (using Docker service name for internal, Windows IP for external)
DATABASE_URL="postgresql://postgres:postgres@postgres:5432/sustainable_transport?schema=public"
DATABASE_URL_EXTERNAL="postgresql://postgres:postgres@${WINDOWS_HOST_IP}:${POSTGRES_PORT}/sustainable_transport?schema=public"

# JWT
JWT_SECRET="your-super-secret-jwt-key-change-this-in-production"
JWT_EXPIRES_IN="7d"

# Redis
REDIS_URL="redis://redis:6379"
REDIS_URL_EXTERNAL="redis://${WINDOWS_HOST_IP}:${REDIS_PORT}"

# API Configuration
PORT=${BACKEND_PORT}
NODE_ENV=development
API_BASE_URL="http://${WINDOWS_HOST_IP}:${BACKEND_PORT}"
API_BASE_URL_INTERNAL="http://backend:${BACKEND_PORT}"

# Mapbox (read from existing config or use placeholder)
MAPBOX_API_KEY="\${MAPBOX_API_KEY:-your-mapbox-access-token}"

# External APIs
METRO_LISBOA_API_KEY="\${METRO_LISBOA_API_KEY:-(optional legacy token)}"
METRO_LISBOA_CLIENT_ID="\${METRO_LISBOA_CLIENT_ID:-your-metro-client-id}"
METRO_LISBOA_CLIENT_SECRET="\${METRO_LISBOA_CLIENT_SECRET:-your-metro-client-secret}"
GIRA_STATIONS_FILE="../EXTERNALS/data/gira/estacoes-gira-1-trimestre-2023.xlsx"
CP_VEHICLES_API_URL="https://comboios.live/api/vehicles"
CP_VEHICLES_CACHE_TTL_MS=30000

# OTP Configuration
# Internal (Docker network): use service name  
# External (from Windows): use Windows host IP
# Note: OTP (Grizzly) serves at root (http://IP:8080), not /otp path
# Backend will append paths like /routers/default/index/graphql
OTP_BASE_URL="http://otp:8080"
OTP_BASE_URL_EXTERNAL="http://${WINDOWS_HOST_IP}:${OTP_PORT}"

# Weather API (optional)
WATHER_API_KEY="\${WATHER_API_KEY:-your-weather-api-key}"
TRANSPORT_API_KEY="\${TRANSPORT_API_KEY:-your-transport-api-key}"

# Network Configuration
WINDOWS_HOST_IP="${WINDOWS_HOST_IP}"
WSL_IP="${WSL_IP}"
EOF

echo -e "${GREEN}✅ Backend .env generated${NC}\n"

# ===========================================
# 5. Generate Frontend config (Dart)
# ===========================================

echo -e "${YELLOW}⚙️  Generating frontend config...${NC}"

# Create config directory if it doesn't exist
mkdir -p "Frontend/lib/config"

FRONTEND_CONFIG_FILE="Frontend/lib/config/app_config.dart"

# Check if mapbox token exists in old file
MAPBOX_TOKEN=$(grep -oP "pk\.[^']+" Frontend/lib/mapbox_config.dart 2>/dev/null || echo "")

cat > "$FRONTEND_CONFIG_FILE" << EOF
// lib/config/app_config.dart
// Auto-generated by spin-up.sh - DO NOT EDIT MANUALLY
// Regenerated on each spin-up

/// Backend API base URL
const String kApiBaseUrl = 'http://${WINDOWS_HOST_IP}:${BACKEND_PORT}';

/// Mapbox access token
const String kMapboxAccessToken = '${MAPBOX_TOKEN:-your-mapbox-access-token}';

/// OTP base URL (for direct access if needed)
const String kOtpBaseUrl = 'http://${WINDOWS_HOST_IP}:${OTP_PORT}';

/// Network configuration
class AppConfig {
  static const String apiBaseUrl = kApiBaseUrl;
  static const String mapboxToken = kMapboxAccessToken;
  static const String otpBaseUrl = kOtpBaseUrl;
  
  // Service URLs
  static const String backendUrl = 'http://${WINDOWS_HOST_IP}:${BACKEND_PORT}';
  static const String otpUrl = 'http://${WINDOWS_HOST_IP}:${OTP_PORT}';
}
EOF

echo -e "${GREEN}✅ Frontend config generated${NC}\n"

# ===========================================
# 6. Update docker-compose.yml with detected IPs
# ===========================================

echo -e "${YELLOW}⚙️  Updating docker-compose environment...${NC}"

# Create a .env file for docker-compose
DOCKER_ENV_FILE=".env.docker"

cat > "$DOCKER_ENV_FILE" << EOF
# Auto-generated by spin-up.sh
WINDOWS_HOST_IP=${WINDOWS_HOST_IP}
WSL_IP=${WSL_IP}
BACKEND_PORT=${BACKEND_PORT}
OTP_PORT=${OTP_PORT}
EOF

echo -e "${GREEN}✅ Docker environment configured${NC}\n"

# ===========================================
# 7. Display Configuration Summary
# ===========================================

echo -e "${BLUE}════════════════════════════════════════${NC}"
echo -e "${BLUE}📋 Configuration Summary${NC}"
echo -e "${BLUE}════════════════════════════════════════${NC}"
echo -e "Windows Host IP:  ${GREEN}${WINDOWS_HOST_IP}${NC}"
echo -e "WSL IP:           ${GREEN}${WSL_IP}${NC}"
echo -e "Backend URL:      ${GREEN}http://${WINDOWS_HOST_IP}:${BACKEND_PORT}${NC}"
echo -e "OTP URL:          ${GREEN}http://${WINDOWS_HOST_IP}:${OTP_PORT}${NC}"
echo -e "Postgres:         ${GREEN}${WINDOWS_HOST_IP}:${POSTGRES_PORT}${NC}"
echo -e "Redis:            ${GREEN}${WINDOWS_HOST_IP}:${REDIS_PORT}${NC}"
echo -e "${BLUE}════════════════════════════════════════${NC}\n"

# ===========================================
# 8. Start Services
# ===========================================

echo -e "${YELLOW}🐳 Starting Docker services...${NC}"

# Check if docker-compose is available
if ! command -v docker-compose &> /dev/null; then
  echo -e "${RED}❌ docker-compose not found. Please install Docker Compose.${NC}"
  exit 1
fi

# Stop existing services if running (for clean restart)
echo -e "${YELLOW}   Stopping existing services (if any)...${NC}"
docker-compose down 2>/dev/null || true

# Start services
echo -e "${YELLOW}   Starting services...${NC}"
docker-compose up -d

echo -e "${GREEN}✅ Services started!${NC}\n"

# ===========================================
# 9. Wait for services to be ready
# ===========================================

echo -e "${YELLOW}⏳ Waiting for services to be ready...${NC}"

# Wait for backend to be ready
# Check from inside Docker container (most reliable)
MAX_ATTEMPTS=30
ATTEMPT=0
BACKEND_READY=false

while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
  # Check from inside the container (most reliable)
  if docker-compose exec -T backend curl -s "http://localhost:${BACKEND_PORT}/health" > /dev/null 2>&1; then
    echo -e "${GREEN}✅ Backend is ready!${NC}"
    BACKEND_READY=true
    break
  fi
  # Fallback: try from WSL localhost
  if curl -s "http://localhost:${BACKEND_PORT}/health" > /dev/null 2>&1; then
    echo -e "${GREEN}✅ Backend is ready!${NC}"
    BACKEND_READY=true
    break
  fi
  ATTEMPT=$((ATTEMPT + 1))
  if [ $((ATTEMPT % 5)) -eq 0 ]; then
    echo -e "   Attempt ${ATTEMPT}/${MAX_ATTEMPTS}... (checking backend logs...)"
    docker-compose logs --tail 3 backend 2>/dev/null | grep -i "running\|started\|error" || true
  else
    echo -e "   Attempt ${ATTEMPT}/${MAX_ATTEMPTS}..."
  fi
  sleep 2
done

if [ "$BACKEND_READY" = false ]; then
  echo -e "${YELLOW}⚠️  Backend health check timed out.${NC}"
  echo -e "${YELLOW}   However, backend may still be running. Check status:${NC}"
  echo -e "${YELLOW}   - docker-compose ps${NC}"
  echo -e "${YELLOW}   - docker-compose logs backend${NC}"
  echo -e "${YELLOW}   - curl http://${WINDOWS_HOST_IP}:${BACKEND_PORT}/health${NC}"
fi

# ===========================================
# 10. Final Summary
# ===========================================

echo -e "\n${GREEN}════════════════════════════════════════${NC}"
echo -e "${GREEN}✅ Spin-Up Complete!${NC}"
echo -e "${GREEN}════════════════════════════════════════${NC}\n"

echo -e "Backend API:      ${BLUE}http://${WINDOWS_HOST_IP}:${BACKEND_PORT}${NC}"
echo -e "Health Check:     ${BLUE}http://${WINDOWS_HOST_IP}:${BACKEND_PORT}/health${NC}"
echo -e "OTP Service:      ${BLUE}http://${WINDOWS_HOST_IP}:${OTP_PORT}${NC}"
echo -e "OTP GraphQL:      ${BLUE}http://${WINDOWS_HOST_IP}:${OTP_PORT}/routers/default/index/graphql${NC}\n"

echo -e "To view logs:     ${YELLOW}docker-compose logs -f${NC}"
echo -e "To stop:          ${YELLOW}docker-compose down${NC}"
echo -e "To restart:        ${YELLOW}./scripts/spin-up.sh${NC}\n"

