# ===========================================
# Modular Spin-Up Script (PowerShell)
# For Windows users who want to run from PowerShell
# ===========================================

Write-Host "🚀 Starting Modular Spin-Up (PowerShell)..." -ForegroundColor Blue
Write-Host ""

# ===========================================
# 1. Detect Windows Host IP
# ===========================================

Write-Host "📡 Detecting Windows host IP..." -ForegroundColor Yellow

$ipconfig = ipconfig | Select-String -Pattern "IPv4" | Select-Object -First 1
$windowsHostIP = ($ipconfig -split ":")[-1].Trim()

if ([string]::IsNullOrWhiteSpace($windowsHostIP)) {
    Write-Host "❌ Could not detect Windows host IP. Please set it manually." -ForegroundColor Red
    exit 1
}

Write-Host "✅ Windows host IP detected: $windowsHostIP" -ForegroundColor Green
Write-Host ""

# ===========================================
# 2. Service Ports Configuration
# ===========================================

$backendPort = 3000
$otpPort = 8080
$postgresPort = 5432
$redisPort = 6379
$mongoPort = 27017

# ===========================================
# 3. Generate Backend .env file
# ===========================================

Write-Host "⚙️  Generating backend/.env..." -ForegroundColor Yellow

$backendEnvContent = @"
# Auto-generated by spin-up.ps1 - DO NOT EDIT MANUALLY
# Regenerated on each spin-up

# Database
DATABASE_URL="postgresql://postgres:postgres@postgres:5432/sustainable_transport?schema=public"
DATABASE_URL_EXTERNAL="postgresql://postgres:postgres@${windowsHostIP}:${postgresPort}/sustainable_transport?schema=public"

# JWT
JWT_SECRET="your-super-secret-jwt-key-change-this-in-production"
JWT_EXPIRES_IN="7d"

# Redis
REDIS_URL="redis://redis:6379"
REDIS_URL_EXTERNAL="redis://${windowsHostIP}:${redisPort}"

# API Configuration
PORT=${backendPort}
NODE_ENV=development
API_BASE_URL="http://${windowsHostIP}:${backendPort}"
API_BASE_URL_INTERNAL="http://backend:${backendPort}"

# Mapbox
MAPBOX_API_KEY="`${MAPBOX_API_KEY:-your-mapbox-access-token}"

# External APIs
METRO_LISBOA_API_KEY="`${METRO_LISBOA_API_KEY:-(optional legacy token)}"
METRO_LISBOA_CLIENT_ID="`${METRO_LISBOA_CLIENT_ID:-your-metro-client-id}"
METRO_LISBOA_CLIENT_SECRET="`${METRO_LISBOA_CLIENT_SECRET:-your-metro-client-secret}"
GIRA_STATIONS_FILE="../EXTERNALS/data/gira/estacoes-gira-1-trimestre-2023.xlsx"
CP_VEHICLES_API_URL="https://comboios.live/api/vehicles"
CP_VEHICLES_CACHE_TTL_MS=30000

# OTP Configuration
OTP_BASE_URL="http://otp:8080/otp"
OTP_BASE_URL_EXTERNAL="http://${windowsHostIP}:${otpPort}/otp"

# Weather API (optional)
WATHER_API_KEY="`${WATHER_API_KEY:-your-weather-api-key}"
TRANSPORT_API_KEY="`${TRANSPORT_API_KEY:-your-transport-api-key}"

# Network Configuration
WINDOWS_HOST_IP="${windowsHostIP}"
"@

$backendEnvContent | Out-File -FilePath "backend\.env" -Encoding utf8 -NoNewline

Write-Host "✅ Backend .env generated" -ForegroundColor Green
Write-Host ""

# ===========================================
# 4. Display Configuration Summary
# ===========================================

Write-Host "════════════════════════════════════════" -ForegroundColor Blue
Write-Host "📋 Configuration Summary" -ForegroundColor Blue
Write-Host "════════════════════════════════════════" -ForegroundColor Blue
Write-Host "Windows Host IP:  $windowsHostIP" -ForegroundColor Green
Write-Host "Backend URL:      http://${windowsHostIP}:${backendPort}" -ForegroundColor Green
Write-Host "OTP URL:          http://${windowsHostIP}:${otpPort}/otp" -ForegroundColor Green
Write-Host "Postgres:         ${windowsHostIP}:${postgresPort}" -ForegroundColor Green
Write-Host "Redis:            ${windowsHostIP}:${redisPort}" -ForegroundColor Green
Write-Host "════════════════════════════════════════" -ForegroundColor Blue
Write-Host ""

# ===========================================
# 5. Start Services (via WSL)
# ===========================================

Write-Host "🐳 Starting Docker services via WSL..." -ForegroundColor Yellow

# Run the bash script in WSL
wsl bash scripts/spin-up.sh

Write-Host ""
Write-Host "✅ Spin-Up Complete!" -ForegroundColor Green
Write-Host ""

